services:
  mysql:
    image: mysql:8.0.32
    container_name: poopmap-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poopmap
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.0-alpine
    container_name: poopmap-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
