spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/daypoo
    username: daypoo
    password: daypoo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPGDialect

  data:
    redis:
      host: localhost
      port: 6380

springdoc:
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html
  api-docs:
    enabled: true
